version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch

workflows:
  build:
    jobs:
      - build:
          context:
            - push-to-dockerhub
jobs:
  build:
    executor: docker-publisher
    working_directory: ~/automation
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t "opinarygmbh/automation:$CIRCLE_SHA1" .
      - run: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push "opinarygmbh/automation:$CIRCLE_SHA1"
      - deploy:
          name: Build and push latest image tag
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t opinarygmbh/automation:latest .
              docker push opinarygmbh/automation:latest    
            fi
